name = "XMag"
license = "MIT"
licenselink = "https://github.com/yihui/hugo-xmag/blob/master/LICENSE.md"
description = "A minimal magazine theme for Hugo"
homepage = "https://xmag.yihui.name"
tags = ["minimal", "magazine", "clean", "simple", "minimalist", "blog"]
features = ["blog", "magazine"]
min_version = "0.18"

[author]
  name = "Yihui Xie"
  homepage = "https://yihui.name"
